let body = document.getElementsByTagName("body")[0];

let dropDown = document.createElement('select');
dropDown.id = 'lang';
dropDown.name = 'lang';
body.appendChild(dropDown);

const languages = [
    ['English', 'English', 'en'],
    ['Afrikaans', 'Afrikaans', 'af'],
    ['Albanian', 'Shqip', 'sq'],
    ['Amharic', 'አማርኛ', 'am'],
    ['Anglo-Saxon', 'Englisc', 'ang'],
    ['Arabic', 'العربية', 'ar'],
    ['Aragonese', 'Aragonés', 'an'],
    ['Armenian', 'Հայերեն', 'hy'],
    ['Aromanian', 'Armãneashce', 'roa-rup'],
    ['Asturian', 'Asturianu', 'ast'],
    ['Aymara', 'Aymar', 'ay'],
    ['Azerbaijani', 'Azərbaycanca', 'az'],
    ['Basque', 'Euskara', 'eu'],
    ['Belarusian', 'Беларуская', 'be'],
    ['Bengali', 'বাংলা', 'bn'],
    ['Bosnian', 'Bosanski', 'bs'],
    ['Breton', 'Brezhoneg', 'br'],
    ['Bulgarian', 'Български', 'bg'],
    ['Burmese', 'မြန်မာဘာသာ', 'my'],
    ['Cantonese', '粵 語', 'yue'],
    ['Catalan', 'Català', 'ca'],
    ['Central Bicolano', 'Bikol', 'bcl'],
    ['Cherokee', 'ᏣᎳᎩ', 'chr'],
    ['Chinese', '中文', 'zh'],
    ['Cornish', 'Kernowek/Karnuack', 'kw'],
    ['Corsican', 'Corsu', 'co'],
    ['Croatian', 'Hrvatski', 'hr'],
    ['Czech', 'Čeština', 'cs'],
    ['Danish', 'Dansk', 'da'],
    ['Divehi', 'ދިވެހިބަސް', 'dv'],
    ['Dutch', 'Nederlands', 'nl'],
    ['Esperanto', 'Esperanto', 'eo'],
    ['Estonian', 'Eesti', 'et'],
    ['Faroese', 'Føroyskt', 'fo'],
    ['Fiji Hindi', 'Fiji Hindi', 'hif'],
    ['Fijian', 'Na Vosa Vakaviti', 'fj'],
    ['Finnish', 'Suomi', 'fi'],
    ['French', 'Français', 'fr'],
    ['Galician', 'Galego', 'gl'],
    ['Georgian', 'ქართული', 'ka'],
    ['German', 'Deutsch', 'de'],
    ['Goan Konkani', 'गोंयची कोंकणी / Gõychi Konknni', 'gom'],
    ['Greek', 'Ελληνικά', 'el'],
    ['Greenlandic', 'Kalaallisut', 'kl'],
    ['Guarani', 'Avañe\'ẽ', 'gn'],
    ['Gujarati', 'ગુજરાતી', 'gu'],
    ['Hausa', 'Hausa / هَوُسَ', 'ha'],
    ['Hebrew', 'עברית', 'he'],
    ['Hindi', 'हिन्दी', 'hi'],
    ['Hungarian', 'Magyar', 'hu'],
    ['Icelandic', 'Íslenska', 'is'],
    ['Ido', 'Ido', 'io'],
    ['Indonesian', 'Bahasa Indonesia', 'id'],
    ['Interlingua', 'Interlingua', 'ia'],
    ['Interlingue', 'Interlingue', 'ie'],
    ['Inuktitut', 'ᐃᓄᒃᑎᑐᑦ', 'iu'],
    ['Inupiak', 'Iñupiatun', 'ik'],
    ['Irish', 'Gaeilge', 'ga'],
    ['Italian', 'Italiano', 'it'],
    ['Japanese', '日本語', 'ja'],
    ['Javanese', 'Basa Jawa', 'jv'],
    ['Kannada', 'ಕನ್ನಡ', 'kn'],
    ['Kashubian', 'Kaszëbsczi', 'csb'],
    ['Kazakh', 'Қазақша', 'kk'],
    ['Khmer', 'ភាសាខ្មែរ', 'km'],
    ['Kinyarwanda', 'Ikinyarwanda', 'rw'],
    ['Kirghiz', 'Кыргызча', 'ky'],
    ['Korean', '한국어', 'ko'],
    ['Kurdish', 'Kurdî / كوردی', 'ku'],
    ['Lao', 'ລາວ', 'lo'],
    ['Latin', 'Latina', 'la'],
    ['Latvian', 'Latviešu', 'lv'],
    ['Limburgish', 'Limburgs', 'li'],
    ['Lingala', 'Lingala', 'ln'],
    ['Lithuanian', 'Lietuvių', 'lt'],
    ['Lojban', 'Lojban', 'jbo'],
    ['Low Saxon', 'Plattdüütsch', 'nds'],
    ['Luxembourgish', 'Lëtzebuergesch', 'lb'],
    ['Macedonian', 'Македонски', 'mk'],
    ['Malagasy', 'Malagasy', 'mg'],
    ['Malay', 'Bahasa Melayu', 'ms'],
    ['Malayalam', 'മലയാളം', 'ml'],
    ['Maltese', 'Malti', 'mt'],
    ['Manx', 'Gaelg', 'gv'],
    ['Maori', 'Māori', 'mi'],
    ['Marathi', 'मराठी', 'mr'],
    ['Min Nan', 'Bân-lâm-gú', 'zh-min-nan'],
    ['Minangkabau', 'Minangkabau', 'min'],
    ['Mongolian', 'Монгол', 'mn'],
    ['Nahuatl', 'Nāhuatl', 'nah'],
    ['Nauruan', 'dorerin Naoero', 'na'],
    ['Nepali', 'नेपाली', 'ne'],
    ['Nias', 'Li Niha', 'nia'],
    ['Norwegian (Bokmål)', 'Norsk (Bokmål)', 'no'],
    ['Norwegian (Nynorsk)', 'Nynorsk', 'nn'],
    ['Occitan', 'Occitan', 'oc'],
    ['Oriya', 'ଓଡ଼ିଆ', 'or'],
    ['Oromo', 'Oromoo', 'om'],
    ['Pashto', 'پښتو', 'ps'],
    ['Persian', 'فارسی', 'fa'],
    ['Polish', 'Polski', 'pl'],
    ['Portuguese', 'Português', 'pt'],
    ['Punjabi', 'ਪੰਜਾਬੀ', 'pa'],
    ['Quechua', 'Runa Simi', 'qu'],
    ['Romanian', 'Română', 'ro'],
    ['Russian', 'Русский', 'ru'],
    ['Samoan', 'Gagana Samoa', 'sm'],
    ['Sango', 'Sängö', 'sg'],
    ['Sanskrit', 'संस्कृतम्', 'sa'],
    ['Saraiki', 'سرائیکی', 'skr'],
    ['Scottish Gaelic', 'Gàidhlig', 'gd'],
    ['Serbian', 'Српски / Srpski', 'sr'],
    ['Serbo-Croatian', 'Srpskohrvatski / Српскохрватски', 'sh'],
    ['Sesotho', 'Sesotho', 'st'],
    ['Shan', 'လိၵ်ႈတႆး', 'shn'],
    ['Shawiya', 'Tacawit', 'shy'],
    ['Sicilian', 'Sicilianu', 'scn'],
    ['Simple English', 'Simple English', 'simple'],
    ['Sindhi', 'سنڌي، سندھی ، सिन्ध', 'sd'],
    ['Sinhalese', 'සිංහල', 'si'],
    ['Slovak', 'Slovenčina', 'sk'],
    ['Slovenian', 'Slovenščina', 'sl'],
    ['Somali', 'Soomaali', 'so'],
    ['Spanish', 'Español', 'es'],
    ['Sundanese', 'Basa Sunda', 'su'],
    ['Swahili', 'Kiswahili', 'sw'],
    ['Swati', 'SiSwati', 'ss'],
    ['Swedish', 'Svenska', 'sv'],
    ['Tagalog', 'Tagalog', 'tl'],
    ['Tajik', 'Тоҷикӣ', 'tg'],
    ['Tamil', 'தமிழ்', 'ta'],
    ['Tatar', 'Tatarça / Татарча', 'tt'],
    ['Telugu', 'తెలుగు', 'te'],
    ['Thai', 'ไทย', 'th'],
    ['Tigrinya', 'ትግርኛ', 'ti'],
    ['Tok Pisin', 'Tok Pisin', 'tpi'],
    ['Tsonga', 'Xitsonga', 'ts'],
    ['Tswana', 'Setswana', 'tn'],
    ['Turkish', 'Türkçe', 'tr'],
    ['Turkmen', 'Türkmen', 'tk'],
    ['Ukrainian', 'Українська', 'uk'],
    ['Upper Sorbian', 'Hornjoserbsce', 'hsb'],
    ['Urdu', 'اردو', 'ur'],
    ['Uyghur', 'ئۇيغۇر تىلى', 'ug'],
    ['Uzbek', 'O‘zbek', 'uz'],
    ['Venetian', 'Vèneto', 'vec'],
    ['Vietnamese', 'Tiếng Việt', 'vi'],
    ['Volapük', 'Volapük', 'vo'],
    ['Walloon', 'Walon', 'wa'],
    ['Welsh', 'Cymraeg', 'cy'],
    ['West Frisian', 'Frysk', 'fy'],
    ['Western Punjabi', 'شاہ مکھی پنجابی (Shāhmukhī Pañjābī)', 'pnb'],
    ['Wolof', 'Wolof', 'wo'],
    ['Yiddish', 'ייִדיש', 'yi'],
    ['Zazaki', 'Zazaki', 'diq'],
    ['Zhuang', 'Cuengh', 'za'],
    ['Zulu', 'isiZulu', 'zu']];

languages.forEach(language => {
    let option = document.createElement('option');
    option.text = (language[0] + " | " + language[1]);
    option.value = language[2]
    dropDown.appendChild(option);
});

chrome.storage.sync.get("language", ({ language }) => {
    dropDown.value = language;
});

dropDown.onchange = function () {
    chrome.storage.sync.set({ 'language': document.getElementById("lang").value });
};